### ISSUE TITLE
Installer Component Build - NSIS Path

### ISSUE THREAD

**Issue by GStegemann** [edwig/ODBCQueryTool#11]
Hello Edwig,

in your Installer Visual Studio Project configuration you are using two different paths depending building the 32 oder 64 bit version of ODBC Query Tool:

- "C:\Program Files (x86)\NSIS\makensis.exe"
- "C:\Program Files\NSIS\makensis.exe"

However, there is no 64 bit version of NSIS. Therefore it is sufficient to build all variants of the ODBC Query Tool Installers using the 32 bit path. A second "64 bit" installation of NSIS is not required.

Best regards,
Gerhard

**Comment by edwig** [comment]
A 64 bit installer is an absolute requirement in my working environments. A 64 bit version starts 64 bits components on MS-WIndows, wheras a 32 bits installer does not!. Because of this fact the NSIS wiki main page (https://nsis.sourceforge.io/Main_Page) points you to a 64 bits installer (https://bitbucket.org/dgolub/nsis64) But lately, this page is not operational any more and you need to go to the wayback machine at web.archive.org to download it from this adres:
https://web.archive.org/web/20160329184013/https://bitbucket.org/dgolub/nsis64
Choose the download link in the ulterior left/down.

I've been using this 2.43 version download for the last ten years in conjunction with the 2.43 version of the 'normal' NSIS.
This relieves me from writing overly complex code (Am I on 32 or 64 bits, program files, registry, starting other programs and so on).

**Comment by edwig** [comment]
Added a file 'Build instructions.txt' in the solution explaining all tools and necessary steps to build the ODBQueryTool.

**Comment by GStegemann** [comment]
I understand your point. But I wouldn't recommend to you an outdated und unsupported version of NSIS. I'm using NSIS 3.10 for my projects. Fortunately my projects are all 32 bit Applications. 

However, 64 bit support is provided by NSIS through Include file "X64.nsh" and command "SetRegView". See e.g. https://nsis-dev.github.io/NSIS-Forums/html/t-301724.html, https://stackoverflow.com/questions/19374453/nsis-installer-define-installer-and-system-x32-x64 or https://stackoverflow.com/questions/1700525/is-it-possible-for-32-bit-nsis-to-launch-a-64-bit-program as suggestion.

The architecture of the application can be passed with the /D switch to makensis.exe, like /DARCH=x86/x64. So it would work in your build setup.

If you are interested I can check your NSIS files what modifications have to be made to support to created 64 bit Installers of ODBCQuery.
